### ISSUE TITLE
Issue with third party like ngrok, pinggy and local tunnel

### ISSUE THREAD

**Issue by khanajan** [zachysaur/Notebooks-for-kaggle#3]
Hey there sir, 
As i have updated to your latest version, thank you 
now i am encountering issues as im unable to access LOCAL TUNNEL - asking for Tunnel password 
Ngrok is not working as it cannot establish link with ngrok agent
well pinggy has become buggy. 
i wanted to bring in your notice sir. thank you once again for this awesome work/help.

**Comment by zachysaur** [comment]
i update notebook with latest version 4.1.4

**Comment by khanajan** [comment]
Thank you Sir!

**Comment by zachysaur** [comment]
that ip asddress is local tunnel password
